# Generated by Django 6.0.1 on 2026-02-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_alter_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
