# Generated by Django 6.0.1 on 2026-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
        ('districts', '0004_alter_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='districts',
            field=models.ManyToManyField(blank=True, help_text='Districts this user (a Bishop) may view. Ignored for other roles.', related_name='bishop_profiles', to='districts.district'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('archbishop', 'Archbishop'), ('bishop', 'Bishop')], default='', max_length=20),
        ),
    ]
