import type { Church } from "@/types/church";

export const mockChurches: Church[] = [
  {
    id: "1",
    name: "KAG Ahero Church",
    location: "Ahero Market Road, Kisumu",
    section: "Kondele Section",
    pastorCount: 2,
    createdAt: "2023-01-15",
  },
  {
    id: "2",
    name: "KAG Bamburi Assembly",
    location: "Bamburi Beach Road, Mombasa",
    section: "Nyali Section",
    pastorCount: 2,
    createdAt: "2023-02-20",
  },
  {
    id: "3",
    name: "KAG Bungoma Town",
    location: "Moi Avenue, Bungoma",
    section: "Bungoma Town Section",
    pastorCount: 3,
    createdAt: "2023-03-10",
  },
  {
    id: "4",
    name: "KAG Buruburu Church",
    location: "Mumias Road, Buruburu",
    section: "Eastlands Section",
    pastorCount: 3,
    createdAt: "2023-04-05",
  },
  {
    id: "5",
    name: "KAG Cathedral Nairobi",
    location: "Ngara Road, Nairobi",
    section: "Nairobi CBD Section",
    pastorCount: 4,
    createdAt: "2022-06-12",
  },
  {
    id: "6",
    name: "KAG Donholm Church",
    location: "Donholm Estate, Nairobi",
    section: "Eastlands Section",
    pastorCount: 2,
    createdAt: "2023-05-18",
  },
  {
    id: "7",
    name: "KAG Eldoret Main",
    location: "Uganda Road, Eldoret",
    section: "Eldoret Town Section",
    pastorCount: 4,
    createdAt: "2022-08-22",
  },
  {
    id: "8",
    name: "KAG Kakamega Central",
    location: "Kakamega-Kisumu Road, Kakamega",
    section: "Kakamega Town Section",
    pastorCount: 3,
    createdAt: "2023-01-30",
  },
  {
    id: "9",
    name: "KAG Kasarani Church",
    location: "Thika Road, Kasarani",
    section: "Kisauni Section",
    pastorCount: 3,
    createdAt: "2023-07-14",
  },
  {
    id: "10",
    name: "KAG Kisumu Central",
    location: "Oginga Odinga Road, Kisumu",
    section: "Kisumu Central Section",
    pastorCount: 5,
    createdAt: "2022-03-25",
  },
  {
    id: "11",
    name: "KAG Kondele Assembly",
    location: "Kondele Market, Kisumu",
    section: "Kondele Section",
    pastorCount: 2,
    createdAt: "2023-09-08",
  },
  {
    id: "12",
    name: "KAG Machakos Town",
    location: "Machakos CBD, Machakos",
    section: "Machakos Town Section",
    pastorCount: 2,
    createdAt: "2023-02-14",
  },
  {
    id: "13",
    name: "KAG Malindi Central",
    location: "Lamu Road, Malindi",
    section: "Malindi Section",
    pastorCount: 1,
    createdAt: "2023-11-01",
  },
  {
    id: "14",
    name: "KAG Nakuru Central",
    location: "Kenyatta Avenue, Nakuru",
    section: "Nakuru Town Section",
    pastorCount: 4,
    createdAt: "2022-05-19",
  },
  {
    id: "15",
    name: "KAG Nyeri Town",
    location: "Kimathi Street, Nyeri",
    section: "Nyeri Town Section",
    pastorCount: 2,
    createdAt: "2023-04-22",
  },
  {
    id: "16",
    name: "KAG Thika Road",
    location: "Thika Superhighway, Nairobi",
    section: "Thika Section",
    pastorCount: 3,
    createdAt: "2023-06-30",
  },
  {
    id: "17",
    name: "KAG Kitale Main",
    location: "Kitale Town Center, Kitale",
    section: "Kitale Town Section",
    pastorCount: 2,
    createdAt: "2023-03-17",
  },
  {
    id: "18",
    name: "KAG Kericho Assembly",
    location: "Kericho Town, Kericho",
    section: "Kericho Town Section",
    pastorCount: 2,
    createdAt: "2023-08-05",
  },
  {
    id: "19",
    name: "KAG Mombasa Central",
    location: "Digo Road, Mombasa",
    section: "Kisauni Section",
    pastorCount: 3,
    createdAt: "2022-10-11",
  },
  {
    id: "20",
    name: "KAG Pipeline Assembly",
    location: "Pipeline Estate, Nairobi",
    section: "Eastlands Section",
    pastorCount: 2,
    createdAt: "2023-12-01",
  },
  {
    id: "21",
    name: "KAG Umoja Church",
    location: "Umoja Estate, Nairobi",
    section: "Eastlands Section",
    pastorCount: 3,
    createdAt: "2023-05-25",
  },
  {
    id: "22",
    name: "KAG Westlands Chapel",
    location: "Westlands Road, Nairobi",
    section: "Nairobi CBD Section",
    pastorCount: 2,
    createdAt: "2023-07-20",
  },
  {
    id: "23",
    name: "KAG Langata Assembly",
    location: "Langata Road, Nairobi",
    section: "Nairobi CBD Section",
    pastorCount: 2,
    createdAt: "2023-10-15",
  },
  {
    id: "24",
    name: "KAG Migori Town",
    location: "Migori CBD, Migori",
    section: "Kisumu Central Section",
    pastorCount: 1,
    createdAt: "2024-01-10",
  },
  {
    id: "25",
    name: "KAG Naivasha Assembly",
    location: "Moi South Lake Road, Naivasha",
    section: "Nakuru Town Section",
    pastorCount: 2,
    createdAt: "2023-09-28",
  },
  {
    id: "26",
    name: "KAG Nanyuki Church",
    location: "Nanyuki Town, Laikipia",
    section: "Nyeri Town Section",
    pastorCount: 1,
    createdAt: "2024-02-05",
  },
  {
    id: "27",
    name: "KAG Ruiru Assembly",
    location: "Ruiru Town, Kiambu",
    section: "Thika Section",
    pastorCount: 2,
    createdAt: "2023-11-22",
  },
  {
    id: "28",
    name: "KAG Athi River",
    location: "Athi River, Machakos",
    section: "Machakos Town Section",
    pastorCount: 2,
    createdAt: "2023-08-14",
  },
  {
    id: "29",
    name: "KAG Webuye Church",
    location: "Webuye Town, Bungoma",
    section: "Bungoma Town Section",
    pastorCount: 1,
    createdAt: "2024-01-25",
  },
  {
    id: "30",
    name: "KAG Mumias Assembly",
    location: "Mumias Town, Kakamega",
    section: "Kakamega Town Section",
    pastorCount: 2,
    createdAt: "2023-06-18",
  },
  {
    id: "31",
    name: "KAG Kilifi Church",
    location: "Kilifi Town, Kilifi",
    section: "Malindi Section",
    pastorCount: 1,
    createdAt: "2024-03-01",
  },
  {
    id: "32",
    name: "KAG Kapenguria Assembly",
    location: "Kapenguria Town, West Pokot",
    section: "Kitale Town Section",
    pastorCount: 1,
    createdAt: "2024-02-18",
  },
  {
    id: "33",
    name: "KAG Litein Church",
    location: "Litein Town, Kericho",
    section: "Kericho Town Section",
    pastorCount: 1,
    createdAt: "2024-01-15",
  },
  {
    id: "34",
    name: "KAG Iten Assembly",
    location: "Iten Town, Elgeyo Marakwet",
    section: "Eldoret Town Section",
    pastorCount: 1,
    createdAt: "2024-03-10",
  },
  {
    id: "35",
    name: "KAG Kisii Central",
    location: "Kisii Town, Kisii",
    section: "Kisumu Central Section",
    pastorCount: 2,
    createdAt: "2023-04-12",
  },
  {
    id: "36",
    name: "KAG Nyamira Assembly",
    location: "Nyamira Town, Nyamira",
    section: "Kondele Section",
    pastorCount: 1,
    createdAt: "2024-02-28",
  },
];
