import type { Pastor, PastorAssignment } from "@/types/church";

export const mockPastors: Pastor[] = [
  { id: "P001", name: "Rev. James Kamau", title: "Reverend" },
  { id: "P002", name: "Bishop Peter Ochieng", title: "Bishop" },
  { id: "P003", name: "Pastor Mary Wanjiku", title: "Pastor" },
  { id: "P004", name: "Pastor Michael Otieno", title: "Pastor" },
  { id: "P005", name: "Rev. Samuel Mwangi", title: "Reverend" },
  { id: "P006", name: "Pastor Grace Akinyi", title: "Pastor" },
  { id: "P007", name: "Pastor Daniel Kibet", title: "Pastor" },
  { id: "P008", name: "Presbyter John Kiprop", title: "Presbyter" },
  { id: "P009", name: "Rev. David Mutua", title: "Reverend" },
  { id: "P010", name: "Bishop Sarah Chebet", title: "Bishop" },
  { id: "P011", name: "Pastor Anne Nyambura", title: "Pastor" },
  { id: "P012", name: "Rev. Joseph Wekesa", title: "Reverend" },
  { id: "P013", name: "Pastor Ruth Atieno", title: "Pastor" },
  { id: "P014", name: "Presbyter George Korir", title: "Presbyter" },
  { id: "P015", name: "Pastor Elizabeth Muthoni", title: "Pastor" },
  { id: "P016", name: "Rev. Patrick Ouma", title: "Reverend" },
  { id: "P017", name: "Pastor Hannah Cherop", title: "Pastor" },
  { id: "P018", name: "Bishop Francis Njoroge", title: "Bishop" },
  { id: "P019", name: "Pastor Stephen Langat", title: "Pastor" },
  { id: "P020", name: "Rev. Catherine Wambui", title: "Reverend" },
];

export const mockPastorAssignments: PastorAssignment[] = [
  {
    id: "A001",
    churchId: "5",
    churchName: "KAG Cathedral Nairobi",
    pastorId: "P001",
    pastorName: "Rev. James Kamau",
    pastorTitle: "Reverend",
    role: "Senior Pastor",
    assignedDate: "1 Feb 2024",
  },
  {
    id: "A002",
    churchId: "5",
    churchName: "KAG Cathedral Nairobi",
    pastorId: "P002",
    pastorName: "Bishop Peter Ochieng",
    pastorTitle: "Bishop",
    role: "Assistant Pastor",
    assignedDate: "15 Mar 2024",
  },
  {
    id: "A003",
    churchId: "5",
    churchName: "KAG Cathedral Nairobi",
    pastorId: "P003",
    pastorName: "Pastor Mary Wanjiku",
    pastorTitle: "Pastor",
    role: "Youth Pastor",
    assignedDate: "1 Apr 2024",
  },
  {
    id: "A004",
    churchId: "5",
    churchName: "KAG Cathedral Nairobi",
    pastorId: "P004",
    pastorName: "Pastor Michael Otieno",
    pastorTitle: "Pastor",
    role: "Treasurer",
    assignedDate: "10 May 2024",
  },
  {
    id: "A005",
    churchId: "22",
    churchName: "KAG Westlands Community",
    pastorId: "P005",
    pastorName: "Rev. Samuel Mwangi",
    pastorTitle: "Reverend",
    role: "Senior Pastor",
    assignedDate: "15 Feb 2024",
  },
  {
    id: "A006",
    churchId: "22",
    churchName: "KAG Westlands Community",
    pastorId: "P006",
    pastorName: "Pastor Grace Akinyi",
    pastorTitle: "Pastor",
    role: "Worship Leader",
    assignedDate: "20 Mar 2024",
  },
  {
    id: "A007",
    churchId: "22",
    churchName: "KAG Westlands Community",
    pastorId: "P007",
    pastorName: "Pastor Daniel Kibet",
    pastorTitle: "Pastor",
    role: "Youth Pastor",
    assignedDate: "1 Jun 2024",
  },
  {
    id: "A008",
    churchId: "19",
    churchName: "KAG Mombasa Central",
    pastorId: "P008",
    pastorName: "Presbyter John Kiprop",
    pastorTitle: "Presbyter",
    role: "Senior Pastor",
    assignedDate: "20 Feb 2024",
  },
  {
    id: "A009",
    churchId: "19",
    churchName: "KAG Mombasa Central",
    pastorId: "P009",
    pastorName: "Rev. David Mutua",
    pastorTitle: "Reverend",
    role: "Assistant Pastor",
    assignedDate: "5 Apr 2024",
  },
  {
    id: "A010",
    churchId: "19",
    churchName: "KAG Mombasa Central",
    pastorId: "P010",
    pastorName: "Bishop Sarah Chebet",
    pastorTitle: "Bishop",
    role: "Associate Pastor",
    assignedDate: "15 May 2024",
  },
  {
    id: "A011",
    churchId: "10",
    churchName: "KAG Kisumu Central",
    pastorId: "P011",
    pastorName: "Pastor Anne Nyambura",
    pastorTitle: "Pastor",
    role: "Senior Pastor",
    assignedDate: "1 Jan 2024",
  },
  {
    id: "A012",
    churchId: "10",
    churchName: "KAG Kisumu Central",
    pastorId: "P012",
    pastorName: "Rev. Joseph Wekesa",
    pastorTitle: "Reverend",
    role: "Assistant Pastor",
    assignedDate: "10 Feb 2024",
  },
  {
    id: "A013",
    churchId: "10",
    churchName: "KAG Kisumu Central",
    pastorId: "P013",
    pastorName: "Pastor Ruth Atieno",
    pastorTitle: "Pastor",
    role: "Youth Pastor",
    assignedDate: "20 Mar 2024",
  },
  {
    id: "A014",
    churchId: "14",
    churchName: "KAG Nakuru Central",
    pastorId: "P014",
    pastorName: "Presbyter George Korir",
    pastorTitle: "Presbyter",
    role: "Senior Pastor",
    assignedDate: "5 Jan 2024",
  },
  {
    id: "A015",
    churchId: "14",
    churchName: "KAG Nakuru Central",
    pastorId: "P015",
    pastorName: "Pastor Elizabeth Muthoni",
    pastorTitle: "Pastor",
    role: "Treasurer",
    assignedDate: "15 Mar 2024",
  },
  {
    id: "A016",
    churchId: "7",
    churchName: "KAG Eldoret Main",
    pastorId: "P016",
    pastorName: "Rev. Patrick Ouma",
    pastorTitle: "Reverend",
    role: "Senior Pastor",
    assignedDate: "1 Mar 2024",
  },
  {
    id: "A017",
    churchId: "7",
    churchName: "KAG Eldoret Main",
    pastorId: "P017",
    pastorName: "Pastor Hannah Cherop",
    pastorTitle: "Pastor",
    role: "Assistant Pastor",
    assignedDate: "20 Apr 2024",
  },
  {
    id: "A018",
    churchId: "7",
    churchName: "KAG Eldoret Main",
    pastorId: "P018",
    pastorName: "Bishop Francis Njoroge",
    pastorTitle: "Bishop",
    role: "Associate Pastor",
    assignedDate: "10 Jun 2024",
  },
  {
    id: "A019",
    churchId: "3",
    churchName: "KAG Bungoma Town",
    pastorId: "P019",
    pastorName: "Pastor Stephen Langat",
    pastorTitle: "Pastor",
    role: "Senior Pastor",
    assignedDate: "15 Jan 2024",
  },
  {
    id: "A020",
    churchId: "3",
    churchName: "KAG Bungoma Town",
    pastorId: "P020",
    pastorName: "Rev. Catherine Wambui",
    pastorTitle: "Reverend",
    role: "Youth Pastor",
    assignedDate: "25 Mar 2024",
  },
  {
    id: "A021",
    churchId: "1",
    churchName: "KAG Ahero Church",
    pastorId: "P001",
    pastorName: "Rev. James Kamau",
    pastorTitle: "Reverend",
    role: "Associate Pastor",
    assignedDate: "5 May 2024",
  },
  {
    id: "A022",
    churchId: "4",
    churchName: "KAG Buruburu Church",
    pastorId: "P003",
    pastorName: "Pastor Mary Wanjiku",
    pastorTitle: "Pastor",
    role: "Senior Pastor",
    assignedDate: "10 Jan 2024",
  },
  {
    id: "A023",
    churchId: "4",
    churchName: "KAG Buruburu Church",
    pastorId: "P006",
    pastorName: "Pastor Grace Akinyi",
    pastorTitle: "Pastor",
    role: "Assistant Pastor",
    assignedDate: "1 Apr 2024",
  },
  {
    id: "A024",
    churchId: "8",
    churchName: "KAG Kakamega Central",
    pastorId: "P012",
    pastorName: "Rev. Joseph Wekesa",
    pastorTitle: "Reverend",
    role: "Senior Pastor",
    assignedDate: "20 Jan 2024",
  },
];
