# Generated by Django 6.0.1 on 2026-01-30 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('pastor_rank', models.CharField(choices=[('ArchBishop', 'ArchBishop'), ('Bishop', 'Bishop'), ('Presbyter', 'Presbyter'), ('Reverend', 'Reverend'), ('Pastor', 'Pastor')], max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+254712345678'", regex='^\\+2547[0-9]{8}$')])),
                ('start_of_service', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pastor',
                'verbose_name_plural': 'Pastors',
                'ordering': ['full_name'],
            },
        ),
    ]
