# Generated by Django 6.0.1 on 2026-05-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastor',
            name='end_of_service',
            field=models.DateField(blank=True, null=True),
        ),
    ]
