# Generated by Django 6.0.1 on 2026-01-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastors', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Senior Pastor', 'Senior Pastor'), ('Assistant Pastor', 'Assistant Pastor'), ('Youth Pastor', 'Youth Pastor'), ('Missions Pastor', 'Missions Pastor'), ('Associate Minister', 'Associate Minister')], max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Role',
                'verbose_name_plural': 'Church Roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='sections.section')),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'ordering': ['church_name'],
            },
        ),
        migrations.CreateModel(
            name='ChurchPastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_pastors', to='churches.church')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_assignments', to='pastors.pastor')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='churches.churchrole')),
            ],
            options={
                'verbose_name': 'Church Pastor Assignment',
                'verbose_name_plural': 'Church Pastor Assignments',
                'ordering': ['church', 'pastor'],
                'unique_together': {('church', 'pastor', 'role')},
            },
        ),
    ]
