# Generated by Django 6.0.1 on 2026-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchrole',
            name='role_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
