# Generated by Django 6.0.1 on 2026-05-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_alter_churchrole_role_name'),
        ('sections', '0002_alter_section_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churches', to='sections.section'),
        ),
        migrations.AlterField(
            model_name='churchpastor',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_pastors', to='churches.church'),
        ),
    ]
