# Generated by Django 6.0.1 on 2026-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Kenya Assemblies of God', max_length=200)),
                ('org_abbreviation', models.CharField(default='KAG', max_length=20)),
                ('admin_name', models.CharField(default='', max_length=150)),
                ('admin_email', models.EmailField(default='', max_length=254)),
                ('admin_phone', models.CharField(default='', max_length=20)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('postal_address', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='English', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=60)),
                ('currency', models.CharField(default='KES', max_length=50)),
                ('retirement_age', models.PositiveIntegerField(default=65)),
                ('min_service_years', models.PositiveIntegerField(default=10)),
                ('fiscal_year_start', models.CharField(default='January', max_length=20)),
                ('default_page_size', models.PositiveIntegerField(default=10)),
                ('notify_new_pastor', models.BooleanField(default=True)),
                ('notify_retirement_alert', models.BooleanField(default=True)),
                ('notify_contribution_reminders', models.BooleanField(default=True)),
                ('notify_assignment_changes', models.BooleanField(default=False)),
                ('notify_report_complete', models.BooleanField(default=True)),
                ('notify_system_updates', models.BooleanField(default=False)),
                ('email_summary_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10)),
                ('account_display_name', models.CharField(default='System Administrator', max_length=150)),
                ('account_email', models.EmailField(default='', max_length=254)),
                ('account_role', models.CharField(default='Super Admin', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
