# Generated by Django 6.0.1 on 2026-06-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='org_logo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
