# Generated by Django 6.0.1 on 2026-08-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_systemsettings_org_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='retirement_age',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
